### ISSUE TITLE
[Question] Saga call with Array

### ISSUE THREAD

**Issue by ng-hai** [r-park/todo-redux-saga#8]
Could you explain to me the [10th line of code](https://github.com/r-park/todo-redux-saga/blob/master/src/core/auth/sagas.js#L10)? I can't figure out why we must use an array here. Thank you.

**Comment by r-park** [comment]
Hi @ng-hai — it's a way to pass the `this` context to `firebaseAuth.signInWithPopup`.

https://github.com/redux-saga/redux-saga/blob/master/docs/api/README.md#callcontext-fn-args

**Comment by ng-hai** [comment]
Thank @r-park, I just thought that it would be the same with calling `axios` method like `yield call(axios.post, someParameters)`.

As your answer, I can rewrite the above method as `yield call([axios, axios.post], someParameters)`, do I right?

**Comment by r-park** [comment]
That should work.
